### ISSUE TITLE
.jpドメイン名のExpires Onは有効期限ではない

### ISSUE THREAD

**Issue by kaoru6** [mochikoAsTech/dnsIntroductoryBook#6]
4.3.1 【ドリル】ドメインの有効期限が分からないの部分について。

jpドメイン名をwhoisで引いたExpires Onは「放っておくとこの日の翌日にドメイン名の登録が失効する」という意味の有効期限とは別物です。

参考: https://help.sakura.ad.jp/hc/ja/articles/206057382-JP%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3%E3%81%AE%E6%9B%B4%E6%96%B0%E8%B2%BB%E7%94%A8%E3%82%92%E6%94%AF%E6%89%95%E3%81%A3%E3%81%9F%E3%81%AE%E3%81%A7%E3%81%99%E3%81%8C-%E6%9C%89%E5%8A%B9%E6%9C%9F%E9%99%90%E3%81%8C%E6%9B%B4%E6%96%B0%E3%81%95%E3%82%8C%E3%81%A6%E3%81%84%E3%81%BE%E3%81%9B%E3%82%93-
https://faq.interlink.or.jp/faq2/View/wcDisplayContent.aspx?id=980

別のTLDのドメイン名を例に出しつつJPドメイン名については脚注でフォローするか、有効期限でなく「毎年の更新時期を知る」という表現であれば不正確ではなくなります(有効期限と誤解される余地は残りますしドリルの役立ち度は減りますが)。

ドメイン名とドメインとの違いについては、このissueではとりあえず放っておきます。

**Comment by mochikoAsTech** [comment]
なるほど！ありがとうございます。
次の改定で取り込ませていただきます。

**Comment by mochikoAsTech** [comment]
@kaoru6 
ちなみに改定後の版でkaoru6さんのお名前をレビュアーの欄にお載せしてもよろしいですか？
（こちらでYESのお返事がなければ、勝手にお載せすることはいたしません）

本名など、こちらの名前で載せて欲しい、というご希望があれば併せてお知らせください。
TwitterのDMでも構いません。よろしくお願いいたします。

**Comment by mochikoAsTech** [comment]
https://github.com/mochikoAsTech/startDNS/issues/2
で修正したのでクローズします。
